[project]
name = "temporal-test-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.0",
    "temporalio>=1.18.2",
    "uvicorn>=0.38.0",
]
